In [1]:
import random

a = random.random() # generates a random float in the range of 0 to 1
print(a)

0.05495157116691962


In [2]:
# Continuous uniform
a = random.uniform(1, 10)
print(a)

2.312367992603817


In [3]:
# Random integer between a and b
a = random.randint(1, 10)
print(a)

8


In [4]:
# Normal random variate
a = random.normalvariate(0, 1)
print(a)

-0.5643010545519848


In [21]:
mylist = list("ABCDEFGH")
print(mylist)
# Pick a random element from the list
a = random.choice(mylist)
print(a)
# If we want to pick multiple elements, we can use 'random.sample' and specify using second argument
# The elements picked are unique
a = random.sample(mylist, 3)
print(a)

# If we want to pick multiple elements that can be the same:
a = random.choices(mylist, k=3)
print(a)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
H
['G', 'E', 'H']
['E', 'B', 'E']


In [25]:
# Shuffle elements in a list
random.shuffle(mylist)
print(mylist)

['E', 'D', 'A', 'B', 'F', 'C', 'H', 'G']


In [26]:
# Use seed to regenerate random numbers
# Random numbers generated by the same seed are always the same
random.seed(1)
print(random.random())
print(random.randint(1, 10))

random.seed(1)
print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2
0.13436424411240122
2


In [39]:
# For security applications such as generate random password, token, we can't use random since
# the numbers are reproducable. 
# In such situations, we should use 'secrets' package
# Reference: https://docs.python.org/3/library/secrets.html
import secrets

a = secrets.randbelow(10)
print(a)

a = secrets.randbits(4)
print(a)

mylist = list("ABCDEFGH")
a = secrets.choice(mylist)
print(a)

1
1
B


In [45]:
# We can use numpy package to generate random numbers

import numpy as np

a = np.random.rand(3)
print(a)

a = np.random.rand(3, 3)
print(a)

a = np.random.randint(0, 10, 3) # excludes 10, last argument specifies size
print(a)

a = np.random.randint(0, 10, (3, 4))
print(a)

[0.01512929 0.27379364 0.28606342]
[[0.83213097 0.67772192 0.93973401]
 [0.67572608 0.63821729 0.33660673]
 [0.32851017 0.19688075 0.93291649]]
[4 9 3]
[[6 9 4 5]
 [4 5 9 0]
 [0 5 5 2]]


In [47]:
# numpy shuffle
arr = np.array([[1,2,2],[4,5,6],[7,8,9]])
print(arr)
# Shuffle only shuffles along the first dimension
np.random.shuffle(arr)
print(arr)

[[1 2 2]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 2]]


In [48]:
# We can also use seed to regenerate results

np.random.seed(1)
print(np.random.rand(3,3))

np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
